name: Java CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build with Gradlec and permission to gradlew
      run: |
        chmod +x ./gradlew
        ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
